/**
 * OpportunityAI Title Cache — Permanent Title Storage
 * 
 * Once a title is generated by the AI for a specific email,
 * it is stored permanently in a JSON file on disk.
 * This ensures titles NEVER change across reloads or server restarts.
 */

import fs from 'fs';
import path from 'path';

const CACHE_DIR = path.join(process.cwd(), '.cache');
const CACHE_FILE = path.join(CACHE_DIR, 'title-cache.json');

interface TitleCacheEntry {
  title: string;
  generatedAt: string;
  method: 'ai' | 'heuristic';
}

interface TitleCacheData {
  [emailId: string]: TitleCacheEntry;
}

function ensureCacheDir(): void {
  if (!fs.existsSync(CACHE_DIR)) {
    fs.mkdirSync(CACHE_DIR, { recursive: true });
  }
}

function readCache(): TitleCacheData {
  try {
    ensureCacheDir();
    if (fs.existsSync(CACHE_FILE)) {
      const data = fs.readFileSync(CACHE_FILE, 'utf-8');
      return JSON.parse(data);
    }
  } catch (err) {
    console.error('[TitleCache] Error reading cache:', err);
  }
  return {};
}

function writeCache(data: TitleCacheData): void {
  try {
    ensureCacheDir();
    fs.writeFileSync(CACHE_FILE, JSON.stringify(data, null, 2), 'utf-8');
  } catch (err) {
    console.error('[TitleCache] Error writing cache:', err);
  }
}

/**
 * Get a cached title for an email ID.
 * Returns null if no cached title exists.
 */
export function getCachedTitle(emailId: string): string | null {
  const cache = readCache();
  const entry = cache[emailId];
  return entry ? entry.title : null;
}

/**
 * Store a generated title in the permanent cache.
 */
export function setCachedTitle(emailId: string, title: string, method: 'ai' | 'heuristic'): void {
  const cache = readCache();
  cache[emailId] = {
    title,
    generatedAt: new Date().toISOString(),
    method
  };
  writeCache(cache);
}

/**
 * Check if a title exists in the cache.
 */
export function hasCachedTitle(emailId: string): boolean {
  const cache = readCache();
  return emailId in cache;
}

/**
 * Clear the entire title cache (useful for debugging).
 */
export function clearTitleCache(): void {
  writeCache({});
}

/**
 * Get all cached titles (useful for debugging).
 */
export function getAllCachedTitles(): TitleCacheData {
  return readCache();
}
